export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const VISION_REQUEST='VISION_REQUEST';
export const VISION_SUCCESS='VISION_SUCCESS';
export const VISION_FAILURE='VISION_FAILURE';


export const IMAGE_REQUEST='IMAGE_REQUEST';
export const IMAGE_SUCCESS='IMAGE_SUCCESS';
export const IMAGE_FAILURE='IMAGE_FAILURE';
